### ISSUE TITLE
 Module does not work: "Unable to resolve module `react-dom/server`"

### ISSUE THREAD

**Issue by CeamKrier** [tom555my/react-native-avataaars#1]
## Expected Behavior
 - 'react-native-avataaars' module should work out-of-the-box.

## Actual Behavior
- Metro builder generating an error upon importing the module and the app crashing

## Steps to Reproduce the Problem

  1. Create a new react-native project via expo CLI / RN CLI
  2. Add 'react-native-avataaars' package to the project.
  3. Import the package to App.js 
  4. Run 'npm run dev' on the terminal.

![image](https://user-images.githubusercontent.com/18554425/59569048-b94a8280-908c-11e9-9e8f-dabd4c9529ec.png)

**Comment by tom555my** [comment]
Try `npm install react-dom --save` or `yarn add react-dom`.
